plugins {
    id 'java-gradle-plugin'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.licenser' version '1.0.1'
    id 'net.minecraftforge.gradleutils' version '[2.3,2.4)'
    id 'com.github.ben-manes.versions' version '0.46.0'
    id 'com.gradleup.shadow' version '8.3.9'
}

version = gradleutils.getTagOffsetBranchVersion('FG_6.0')
logger.lifecycle('Version: ' + version + ' Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

changelog {
    from '6.0'
    publishAll = false
}
sourceSets {
    common
    mcp
    patcher
    userdev
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
    withSourcesJar()
}

configurations {
    configureEach {
        exclude group: 'org.ow2.asm'
    }
    shade
    commonCompileOnly.extendsFrom shade
    mcpCompileOnly.extendsFrom shade
    patcherCompileOnly.extendsFrom shade
    userdevCompileOnly.extendsFrom shade
    
    mcpImplementation.extendsFrom commonImplementation
    patcherImplementation.extendsFrom commonImplementation
    userdevImplementation.extendsFrom mcpImplementation
    implementation.extendsFrom mcpImplementation, patcherImplementation, userdevImplementation
}

tasks.named('shadowJar') {
    mergeServiceFiles()
    configurations = [project.configurations.shade]
    for (def pkg : [
        'codechicken.diffpatch', 
        'codechicken.repack.it.unimi.dsi.fastutil',
        'codechicken.repack.joptsimple',
        'codechicken.repack.org.apache.commons',
        'codechicken.repack.org.tukaani.xz',
        'com.google', 
        'com.machinezoo.noexception',
        'de.siegmar.fastcsv',
        'net.minecraftforge.artifactural',
        'net.minecraftforge.fml.unsafe',
        'net.minecraftforge.jarjar',
        'net.minecraftforge.srgutils', 
        'org.apache.commons', 
        'org.apache.http', 
        'org.apache.maven', 
        'org.checkerframework', 
        'org.codehaus.plexus', 
        'org.slf4j'
    ]) {
        relocate(pkg, 'net.minecraftforge.gradle.reloc.' + pkg.split('\\.').last())
    }
    from sourceSets.common.output
    from sourceSets.mcp.output
    from sourceSets.patcher.output
    from sourceSets.userdev.output
    archiveClassifier = ''
}

tasks.named('jar', Jar) {
    archiveClassifier = 'slim'
    from sourceSets.common.output
    from sourceSets.mcp.output
    from sourceSets.patcher.output
    from sourceSets.userdev.output
}

tasks.named('sourcesJar', Jar).configure {
    from sourceSets.common.allJava
    from sourceSets.mcp.allJava
    from sourceSets.patcher.allJava
    from sourceSets.userdev.allJava
}

repositories {
    mavenLocal()
    maven gradleutils.forgeMaven
}

license {
    header = file('HEADER')
    exclude '**/*.properties'
    exclude 'net/minecraftforge/gradle/common/diff/'
    exclude 'net/minecraftforge/gradle/common/util/JavaVersionParser.java'
}

tasks.named('wrapper', Wrapper).configure {
    gradleVersion = '8.4'
    distributionType = Wrapper.DistributionType.ALL
}

dependencies {
    shade 'commons-io:commons-io:2.11.0'
    shade 'com.google.code.gson:gson:2.10.1'
    shade 'com.google.guava:guava:31.1-jre'
    shade 'de.siegmar:fastcsv:2.2.1'
    shade('net.minecraftforge:artifactural:3.0.20') {
        transitive = false
    }
    shade('net.minecraftforge:unsafe:0.2.0') {
        transitive = false
    }
    shade 'org.apache.maven:maven-artifact:3.9.1'
    shade 'org.apache.httpcomponents:httpclient:4.5.14'
    shade 'net.minecraftforge:srgutils:0.5.10'
    shade('net.minecraftforge:DiffPatch:2.0.12:all') {
        transitive = false
    }
    
    shade 'net.minecraftforge:JarJarMetadata:0.3.19'
    shade 'net.minecraftforge:JarJarSelector:0.3.19'
    
    commonImplementation gradleApi()

    mcpImplementation sourceSets.common.output
    patcherImplementation sourceSets.mcp.output
    patcherImplementation sourceSets.common.output
    userdevImplementation sourceSets.mcp.output
    userdevImplementation sourceSets.common.output
}

gradlePlugin {
    plugins {
        mcp {
            id = 'net.minecraftforge.gradle.mcp'
            implementationClass = 'net.minecraftforge.gradle.mcp.MCPPlugin'
        }
        patcher {
            id = 'net.minecraftforge.gradle.patcher'
            implementationClass = 'net.minecraftforge.gradle.patcher.PatcherPlugin'
        }
        userdev {
            id = 'net.minecraftforge.gradle'
            implementationClass = 'net.minecraftforge.gradle.userdev.UserDevPlugin'
        }
    }
    automatedPublishing = true
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            // Automated publishing declares the java component for us

            project.changelog.publish(it)
        }
    }
    repositories {
        maven gradleutils.getPublishingForgeMaven()
    }
}
