pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://nexus.covers1624.net/repository/maven-releases/' } // Need for DiffPatch
    }
    includeBuild('../../')
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'fg-test-vanilla'
